services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    command: ["sh", "-c", "mvn -q -DskipTests package && java -jar target/teste-pratico-1.0.0.jar"]

  test:
    profiles: ["test"]
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    command: ["mvn", "clean", "test"]
